SET VERIFY OFF;
CLEAR SCREEN
CLEAR BREAKS
CLEAR COMPUTES
CLEAR COLUMNS

SET LINESIZE 65
SET PAGESIZE 10
TTITLE CENTER '------------------------' SKIP1 CENTER '| BUSQUEDA DE EDITORIAL |' SKIP1 CENTER '------------------------' SKIP2 CENTER
SET HEADSEP |

COLUMN CIF HEADING 'CIF' FORMAT A6 TRUNCATED
COLUMN NOMBRE HEADING 'Editorial' FORMAT A20 TRUNCATED
COLUMN PAIS HEADING 'Pais' FORMAT A10 TRUNCATED
COLUMN CIUDAD HEADING 'Ciudad' FORMAT A10 TRUNCATED
COLUMN CODIGO_POSTAL HEADING 'Codigo postal'

ACCEPT CODIGO PROMPT 'Introduce la editorial a buscar (PT00X):'
SELECT * FROM EDITORIAL 
WHERE CIF = UPPER('&CODIGO');