SET VERIFY OFF;
CLEAR SCREEN
CLEAR BREAKS
CLEAR COMPUTES
CLEAR COLUMNS

SET LINESIZE 30
SET PAGESIZE 10
TTITLE CENTER '--------------------' SKIP1 CENTER '| BUSQUEDA DE TEMA |' SKIP1 CENTER '--------------------' SKIP2 CENTER
SET HEADSEP |

COLUMN CODIGO HEADING 'Codigo' FORMAT A6 TRUNCATED
COLUMN NOMBRE HEADING 'Tema' FORMAT A10 TRUNCATED
COLUMN UBICACION HEADING 'Ubicacion' FORMAT A10 TRUNCATED

ACCEPT NB PROMPT 'Introduce el tema a buscar (TERROR):'
SELECT * FROM TEMA 
WHERE NOMBRE = UPPER('&NB');
