SET VERIFY OFF;
CLEAR SCREEN
CLEAR BREAKS
CLEAR COMPUTES
CLEAR COLUMNS

SET LINESIZE 50
SET PAGESIZE 10
TTITLE CENTER '--------------------' SKIP1 CENTER '| BUSQUEDA DE AUTOR |' SKIP1 CENTER '--------------------' SKIP2 CENTER
SET HEADSEP |

COLUMN CODIGO HEADING 'Codigo' FORMAT A6 TRUNCATED
COLUMN APENOM HEADING 'Nombre del autor' FORMAT A20 TRUNCATED
COLUMN PAIS HEADING 'Pais' FORMAT A10 TRUNCATED
COLUMN ALIAS HEADING 'Alias' FORMAT A10 TRUNCATED

ACCEPT CD PROMPT 'Introduce el autor a buscar (Ej: 001ML):'
SELECT * FROM AUTOR 
WHERE CODIGO = UPPER('&CD');